version: "2"
services:
  pdns:
    image: vognev/pdns:dev
    command: sleep infinity
    working_dir: /app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/app
    network_mode: host
    build:
      context: .
